apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcpip.serviceAccountName" . }}
  labels:
    {{- include "mcpip.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
