#!/usr/bin/env python3
"""Package and verify the MCPIP public production distribution.

This repository **is** the public distribution. The maintainers' internal
business material (strategy, roadmap, pricing, narrative deck, competitive
review, unbuilt managed-cloud design) was removed when it was published, and
this script is what keeps it removed: it assembles the tree into a
deterministic, verified ZIP and refuses to write one if any of that material —
or a reference to it — has come back.

    python scripts/build_production_package.py                  # -> dist/mcpip-<version>-production.zip
    python scripts/build_production_package.py --check          # verify only; write nothing
    python scripts/build_production_package.py --manifest       # refresh PACKAGE_MANIFEST.json in place
    python scripts/build_production_package.py --keep-tree      # also leave the staged tree for inspection

What the build guarantees, and fails loudly rather than silently degrades:

* **Allowlist, not denylist.** A new top-level file or directory is *excluded*
  until it is listed here. Nothing leaks into a public release because someone
  forgot to update an ignore rule.
* **Byte-exact.** The package is a copy, not a transformation — every packaged
  file is identical to the file in this tree. So ``PACKAGE_MANIFEST.json``
  describes both, and ``sha256sum`` against a checkout is a valid audit.
* **No internal reference.** The packaged tree contains zero mentions of any
  withheld document or path, and every relative Markdown link between packaged
  documents resolves (§ verify).
* **Determinism.** Sorted traversal and fixed archive timestamps: the same tree
  produces a byte-identical ZIP, so the package hash is reviewable.

``PACKAGE_MANIFEST.json`` records the SHA-256 of every packaged file, the source
commit, and the withheld list — the package states plainly what was left out of it.

Historical note, because its absence is conspicuous: this script once carried a
rewrite pass (declared line edits, section drops, citation substitution) that
converted the private working tree into the public one. That conversion happened
once, at publication. Keeping the rules afterwards did not preserve anything —
their anchors pointed at prose the rewrite itself had already replaced, so the
build could no longer run at all, and ``PACKAGE_MANIFEST.json`` became
unregenerable. What survives here is the half that has a job in a public
repository: verification.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import posixpath
import re
import shutil
import subprocess
import sys
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent

# --------------------------------------------------------------------------
# 1. What ships.  Allowlist — anything not named here is excluded by default.
# --------------------------------------------------------------------------

INCLUDE_ROOT_FILES: tuple[str, ...] = (
    # Product entrypoints + shared primitives.
    "main.py",
    "interfaces.py",
    # Packaging / build / runtime.
    "pyproject.toml",
    "requirements.txt",
    "requirements-dev.txt",
    "VERSION",
    "Dockerfile",
    ".dockerignore",
    "docker-compose.yml",
    "docker-compose.prod.yml",
    "install.sh",
    ".gitignore",
    ".mcp.json",
    # Product & security documentation that stays at the root by convention:
    # README is the landing page, LICENSE drives licence detection, SECURITY.md is
    # GitHub's security-policy surface. The long-form security, operator, policy and
    # community-health documents live under docs/ and .github/ and are picked up by
    # INCLUDE_DIRS — listing them here as well would double-count them.
    "README.md",
    "CHANGELOG.md",
    "SECURITY.md",
    "LICENSE",
)

INCLUDE_DIRS: tuple[str, ...] = (
    ".github",       # CI is part of the verifiability story — it must be readable.
    "app",
    "audit",
    "auth",
    "bridge",
    "core",
    "dashboard",
    "deploy",        # chart/ + k8s/ + redis.conf + the production env template
    "docs",
    "load",          # k6 suite behind docs/evidence/LOAD_AT_SCALE.md — the numbers must be re-runnable.
    "mcpip_verify",
    "models",
    "obfuscator",
    "packaging",
    "release",       # signed manifests + public verification keys; `mcpip verify` needs them.
    "rust",
    "scripts",
    "sdk",
    "services",
    "tests",         # you should not have to trust an authorizer whose tests you cannot run.
    "training",
)

#: Generated by this script rather than selected from the tree. Named so that
#: ``report_unreviewed`` does not flag the file the build itself writes.
GENERATED_ROOT_FILES: tuple[str, ...] = ("PACKAGE_MANIFEST.json",)

# Internal-only paths, named explicitly so the manifest can state what was held
# back rather than leaving the reader to infer it from an absence.
WITHHELD_PATHS: tuple[str, ...] = (
    ".claude/",   # agent context lake — maintainer tooling, not product
    "CLAUDE.md",  # agent instructions
)

#: The one carve-out from ``.claude/``: a Claude Code skill is only discoverable
#: at ``.claude/skills/<name>/``, so shipping the load-test skill means shipping
#: it from there. Named as an exception rather than by loosening the rule above,
#: because "everything under .claude/ is withheld except this" is a claim a
#: reviewer can check, and "some of .claude/ ships" is not.
WITHHELD_EXCEPTIONS: tuple[str, ...] = (".claude/skills/mcpip-load-test/",)

# --------------------------------------------------------------------------
# 2. Internal material that must not reappear.
#
# These documents were withheld at publication. The strings below are what a
# reference to one looks like; finding any of them in a packaged file means a
# citation has come back, and the build stops rather than shipping a link into
# material the reader does not have.
# --------------------------------------------------------------------------

WITHHELD_DOCS: tuple[str, ...] = (
    "DX_COMPETITIVE_REPORT.md",
    "GTM_PRICING.md",
    "MANAGED_CLOUD_ARCHITECTURE.md",
    "PITCH_DECK.md",
    "ROADMAP.md",
    "SOC2_READINESS.md",
    "STRATEGY.md",
)

WITHHELD_DOC_PATHS: frozenset[str] = frozenset(f"docs/{name}" for name in WITHHELD_DOCS)

# --------------------------------------------------------------------------
# 3. Build hygiene — never-ship artifacts.
# --------------------------------------------------------------------------

PRUNE_DIR_NAMES: frozenset[str] = frozenset(
    {
        ".git", ".venv", "venv", "node_modules", "dist", "build", "target", "gen",
        "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".keys",
        ".idea", ".vscode",
    }
)
PRUNE_DIR_SUFFIXES: tuple[str, ...] = (".egg-info",)
PRUNE_FILE_SUFFIXES: tuple[str, ...] = (
    ".pyc", ".pyo", ".pyd", ".so", ".tsbuildinfo", ".anchor", ".log", ".rdb",
    ".pem", ".key",  # private key material must never enter a distribution
)
PRUNE_FILE_NAMES: frozenset[str] = frozenset(
    {".DS_Store", "Thumbs.db", "dump.rdb", "mcpip_worm.jsonl", "mcpip-workspace-plan.json"}
)
# Public verification keys are the deliberate exception to the *.pem prune:
# `mcpip verify` and the license gate need them, and they are public by design.
PRUNE_EXCEPTIONS: tuple[str, ...] = ("release/keys/",)

TEXT_SUFFIXES: frozenset[str] = frozenset(
    {
        ".md", ".py", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".json", ".yml", ".yaml",
        ".toml", ".cfg", ".ini", ".txt", ".sh", ".rs", ".html", ".css", ".conf", ".rb",
    }
)


class BuildError(RuntimeError):
    """A packaging invariant failed. The build stops; nothing is written."""


# --------------------------------------------------------------------------
# 4. Selection
# --------------------------------------------------------------------------


def _is_pruned(rel: str, name: str, *, is_dir: bool) -> bool:
    if any(rel.startswith(keep) for keep in PRUNE_EXCEPTIONS):
        return False
    if is_dir:
        return name in PRUNE_DIR_NAMES or name.endswith(PRUNE_DIR_SUFFIXES)
    return name in PRUNE_FILE_NAMES or name.endswith(PRUNE_FILE_SUFFIXES)


def _is_withheld(rel: str) -> bool:
    if any(rel == p or rel.startswith(p) for p in WITHHELD_EXCEPTIONS):
        return False
    return any(rel == p or rel.startswith(p) for p in WITHHELD_PATHS)


def _walk(root: Path, base: Path) -> Iterable[Path]:
    """Yield packageable files under ``root``, deterministically ordered."""
    for entry in sorted(root.iterdir(), key=lambda p: p.name):
        rel = entry.relative_to(base).as_posix()
        if _is_pruned(rel, entry.name, is_dir=entry.is_dir()):
            continue
        if entry.is_symlink():          # never follow a link out of the tree
            continue
        if entry.is_dir():
            yield from _walk(entry, base)
        elif entry.is_file():
            yield entry


def select_files(repo: Path) -> list[str]:
    selected: list[str] = []
    for name in INCLUDE_ROOT_FILES:
        path = repo / name
        if not path.is_file():
            raise BuildError(f"allowlisted root file is missing: {name}")
        selected.append(name)

    roots = list(INCLUDE_DIRS) + [p.rstrip("/") for p in WITHHELD_EXCEPTIONS]
    for name in roots:
        directory = repo / name
        if not directory.is_dir():
            raise BuildError(f"allowlisted directory is missing: {name}")
        for path in _walk(directory, repo):
            rel = path.relative_to(repo).as_posix()
            if rel in WITHHELD_DOC_PATHS or _is_withheld(rel):
                continue
            selected.append(rel)
    return sorted(set(selected))


def report_unreviewed(repo: Path, selected: Iterable[str]) -> list[str]:
    """Top-level entries that are neither allowlisted nor deliberately withheld.

    Not an error — a new file appearing here means someone added something the
    allowlist has not yet considered, which is exactly the state this build is
    designed to surface rather than resolve on its own.
    """
    known = set(INCLUDE_ROOT_FILES) | set(INCLUDE_DIRS) | set(GENERATED_ROOT_FILES)
    known |= {p.rstrip("/") for p in WITHHELD_PATHS}
    unreviewed = []
    for entry in sorted(repo.iterdir(), key=lambda p: p.name):
        if entry.name in known or entry.name == ".git":
            continue
        if _is_pruned(entry.name, entry.name, is_dir=entry.is_dir()):
            continue
        unreviewed.append(entry.name + ("/" if entry.is_dir() else ""))
    return unreviewed


# --------------------------------------------------------------------------
# 5. Verification
# --------------------------------------------------------------------------

_MD_LINK = re.compile(r"\[[^\]\n]*\]\(([^)\s]+)")

#: Files that legitimately *name* what the distribution holds back: the manifest
#: enumerates it, and this script defines it. Scanning them for the names they
#: exist to record would make the check unsatisfiable.
_SELF_REFERENTIAL: frozenset[str] = frozenset(
    {"PACKAGE_MANIFEST.json", "scripts/build_production_package.py"}
)


def verify(stage: Path, files: list[str]) -> list[str]:
    """Assert the package is internally consistent. Returns non-fatal warnings."""
    warnings: list[str] = []
    packaged = set(files)
    forbidden = WITHHELD_DOCS + tuple(
        p.rstrip("/") for p in WITHHELD_PATHS
        if not any(e.startswith(p) for e in WITHHELD_EXCEPTIONS)
    )

    for rel in files:
        path = stage / rel
        if path.suffix not in TEXT_SUFFIXES:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue

        if rel not in _SELF_REFERENTIAL:
            for token in forbidden:
                if token in text:
                    line = next(
                        (n for n, l in enumerate(text.splitlines(), 1) if token in l), 0
                    )
                    raise BuildError(
                        f"{rel}:{line} references withheld material {token!r} — a citation "
                        "into material the reader does not have; remove it or ship the target"
                    )

        if path.suffix != ".md":
            continue
        for target in _MD_LINK.findall(text):
            if target.startswith(("http://", "https://", "#", "mailto:")):
                continue
            clean = target.split("#", 1)[0]
            if not clean or not clean.endswith(".md"):
                continue
            # Lexical normalization only — never touches the filesystem, so the
            # result cannot depend on the caller's working directory.
            resolved = posixpath.normpath(posixpath.join(posixpath.dirname(rel), clean))
            if resolved not in packaged:
                warnings.append(f"{rel}: relative link does not resolve in-package -> {target}")
    return warnings


# --------------------------------------------------------------------------
# 6. Build
# --------------------------------------------------------------------------


@dataclass
class BuildResult:
    version: str
    files: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    unreviewed: list[str] = field(default_factory=list)
    archive: Optional[Path] = None
    stage: Optional[Path] = None
    manifest: Optional[Path] = None


def _git(repo: Path, *args: str) -> Optional[str]:
    try:
        out = subprocess.run(
            ["git", *args], cwd=repo, capture_output=True, text=True, timeout=15, check=False
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return out.stdout.strip() or None if out.returncode == 0 else None


def build_manifest(repo: Path, version: str, files: list[str]) -> dict[str, object]:
    """The manifest for ``files``, hashed from the working tree.

    Hashing the source rather than the staged copy is sound precisely because the
    build no longer transforms anything: the two are the same bytes. It also means
    ``--manifest`` can refresh the committed manifest without staging a tree.
    """
    return {
        "package": "mcpip",
        "version": version,
        "distribution": "public production distribution",
        "license": {
            "core": "BSL-1.1 (see LICENSE; converts to Apache-2.0 on 2030-07-16)",
            "sdk/python, sdk/typescript": "Apache-2.0",
        },
        "source": {
            "repository": "https://github.com/mcpip-security/mcpip",
            "commit": _git(repo, "rev-parse", "HEAD"),
            "branch": _git(repo, "rev-parse", "--abbrev-ref", "HEAD"),
            # A committed manifest cannot name the commit that contains it, so this is
            # the HEAD the digests were taken against. Stated rather than left for a
            # reviewer to discover when the hash does not resolve to these bytes.
            "note": "HEAD at generation time; the commit that records this manifest is its child",
        },
        "excluded": {
            "reason": "maintainers' internal business and agent-tooling material; not part of the product",
            "documents": sorted(WITHHELD_DOC_PATHS),
            "paths": sorted(WITHHELD_PATHS),
            "path_exceptions": sorted(WITHHELD_EXCEPTIONS),
        },
        "file_count": len(files),
        "files": {rel: hashlib.sha256((repo / rel).read_bytes()).hexdigest() for rel in files},
    }


def _write_json(path: Path, doc: dict[str, object]) -> None:
    path.write_text(json.dumps(doc, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def build(
    repo: Path,
    out_dir: Path,
    *,
    check_only: bool,
    keep_tree: bool,
    manifest_only: bool = False,
) -> BuildResult:
    version = (repo / "VERSION").read_text(encoding="utf-8").strip()
    files = select_files(repo)
    result = BuildResult(version=version, unreviewed=report_unreviewed(repo, files))
    manifest = build_manifest(repo, version, files)

    if manifest_only:
        # Verify against the working tree itself — a byte-exact package makes the
        # two indistinguishable, so there is nothing to stage.
        result.warnings = verify(repo, files)
        target = repo / "PACKAGE_MANIFEST.json"
        _write_json(target, manifest)
        result.files = files + ["PACKAGE_MANIFEST.json"]
        result.manifest = target
        return result

    stage_root = out_dir / f"mcpip-{version}"
    if stage_root.exists():
        shutil.rmtree(stage_root)
    stage_root.mkdir(parents=True)

    for rel in files:
        src, dst = repo / rel, stage_root / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)

    _write_json(stage_root / "PACKAGE_MANIFEST.json", manifest)
    files.append("PACKAGE_MANIFEST.json")

    result.files = files
    result.warnings = verify(stage_root, files)
    result.stage = stage_root

    if check_only:
        shutil.rmtree(stage_root)
        result.stage = None
        return result

    archive = out_dir / f"mcpip-{version}-production.zip"
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for rel in sorted(files):
            info = zipfile.ZipInfo(f"mcpip-{version}/{rel}", date_time=(1980, 1, 1, 0, 0, 0))
            source = stage_root / rel
            info.external_attr = (0o755 if source.stat().st_mode & 0o100 else 0o644) << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            zf.writestr(info, source.read_bytes())
    result.archive = archive

    if not keep_tree:
        shutil.rmtree(stage_root)
        result.stage = None
    return result


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--out-dir", type=Path, default=REPO_ROOT / "dist")
    parser.add_argument("--check", action="store_true", help="verify only; write no archive")
    parser.add_argument(
        "--manifest",
        action="store_true",
        help="refresh PACKAGE_MANIFEST.json in the working tree; write no archive",
    )
    parser.add_argument("--keep-tree", action="store_true", help="leave the staged tree in place")
    args = parser.parse_args(argv)

    if not args.manifest:
        args.out_dir.mkdir(parents=True, exist_ok=True)
    try:
        result = build(
            REPO_ROOT,
            args.out_dir,
            check_only=args.check,
            keep_tree=args.keep_tree,
            manifest_only=args.manifest,
        )
    except BuildError as exc:
        print(f"FAILED: {exc}", file=sys.stderr)
        return 1

    print(f"mcpip {result.version} — {len(result.files)} files")
    print(f"  withheld documents : {', '.join(sorted(WITHHELD_DOC_PATHS))}")
    print(f"  withheld paths     : {', '.join(sorted(WITHHELD_PATHS))}")
    print(f"  path exceptions    : {', '.join(sorted(WITHHELD_EXCEPTIONS))}")
    for entry in result.unreviewed:
        print(f"  NOT ALLOWLISTED (held back): {entry}")
    for warning in result.warnings:
        print(f"  warning: {warning}")
    if result.manifest:
        print(f"  manifest           : {result.manifest}")
    if result.stage:
        print(f"  staged tree        : {result.stage}")
    if result.archive:
        digest = hashlib.sha256(result.archive.read_bytes()).hexdigest()
        size = result.archive.stat().st_size
        print(f"  archive            : {result.archive} ({size:,} bytes)")
        print(f"  sha256             : {digest}")
    elif not result.manifest:
        print("  check only — no archive written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
